/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import mundialag.*;
import com.csvreader.CsvReader;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.jgap.Configuration;

/**
 *
 * @author Byron Lima
 * @author Gabriela Rodríguez
 */
public class MenuBrasil extends javax.swing.JFrame {

    DefaultListModel modelo = new DefaultListModel();
    List<Equipos> equipos = new ArrayList<Equipos>();
    TestEquiposFitness partidos = new TestEquiposFitness();

    /**
     * Creates new form MenuBrasil
     */
    public MenuBrasil() {
        initComponents();
        setBackground(Color.white);

        try {

            CsvReader equipos_import = new CsvReader(System.getProperty("user.dir") + "/src/archivos/Mundial.csv");

            while (equipos_import.readRecord()) {
                String nombre = equipos_import.get(0);
                String ranking = equipos_import.get(1);
                String grupo = equipos_import.get(2);
                String copas = equipos_import.get(3);
                String partido1 = equipos_import.get(4);
                String partido2 = equipos_import.get(5);
                String partido3 = equipos_import.get(6);
                equipos.add(new Equipos(nombre, ranking, grupo, copas, partido1, partido2, partido3));
                System.out.println("TOTAL INICIAL " + equipos.size() + nombre);
            }

            equipos_import.close();

            int cont = 1;
            for (Equipos eq : equipos) {

//	            System.out.println(cont + "" +eq.getNombre()+ " ; " + eq.getRanking()+ " ; "
//	            + eq.getGrupo()+ " ; " + eq.getNumCopas()+ " ; " + eq.getPartido1() + " ; " + eq.getPartido2() + " ; " + eq.getPartido3());
                cont++;
                modelo.addElement(eq.getNombre());
            }
            listEquipos.setModel(modelo);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtp3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtp2 = new javax.swing.JLabel();
        txtcopasg = new javax.swing.JLabel();
        txtp1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtranking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEquipos = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfitness = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtfitness01 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        tfranking = new javax.swing.JTextField();
        tfcopas = new javax.swing.JTextField();
        tf01 = new javax.swing.JTextField();
        tf02 = new javax.swing.JTextField();
        tf03 = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtganadores01 = new javax.swing.JTextArea();
        fit = new javax.swing.JLabel();
        txtFit01 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtconsola = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfgrupo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mundial Brasil 2014");
        setResizable(false);

        txtp3.setName("txtp3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ranking en la FIFA:");

        txtp2.setName("txtp3"); // NOI18N

        txtcopasg.setName("txtcopasg"); // NOI18N

        txtp1.setName("txtp1"); // NOI18N

        txtnombre.setName("txtnombre"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre del equipo:");

        txtranking.setName("txtranking"); // NOI18N

        listEquipos.setName(""); // NOI18N
        listEquipos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                listEquiposComponentAdded(evt);
            }
        });
        listEquipos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEquiposValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEquipos);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Partido 2:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Partido 3:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Copas Ganadas:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Partido 1:");

        jLabel1.setText("Listado de Equipos para BRASIL 2014");

        jLabel2.setFont(new java.awt.Font("Terminal Dosis", 1, 36)); // NOI18N
        jLabel2.setText("BRASIL 2014");

        jButton1.setText("Realizar Pronostico");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Fitness:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Posibles Ganadores:");

        btnguardar.setText("Guardar Cambio");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtganadores01.setColumns(20);
        txtganadores01.setRows(5);
        jScrollPane2.setViewportView(txtganadores01);

        txtFit01.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFit01.setForeground(new java.awt.Color(255, 0, 0));

        txtconsola.setColumns(20);
        txtconsola.setRows(5);
        jScrollPane3.setViewportView(txtconsola);

        jLabel11.setFont(new java.awt.Font("Terminal Dosis", 1, 18)); // NOI18N
        jLabel11.setText("Consola del Programa");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("GRUPO");

        tfgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgrupoActionPerformed(evt);
            }
        });

        jButton2.setLabel("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtFit01))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtranking)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfranking, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtcopasg)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfcopas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf03, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf02, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tfgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(62, 62, 62))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnguardar)
                                .addGap(164, 164, 164))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(fit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfitness01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfitness))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtp1)
                                    .addComponent(txtp2)
                                    .addComponent(txtp3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jLabel11)))
                        .addContainerGap(31, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(326, 326, 326))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtnombre)
                                    .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtranking)
                                    .addComponent(tfranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtcopasg)
                                    .addComponent(tfcopas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tf02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tf03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnguardar)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFit01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtp3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtfitness)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfitness01)
                                    .addComponent(fit)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listEquiposValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEquiposValueChanged

        tfnombre.setText(equipos.get(listEquipos.getSelectedIndex()).getNombre());
        tfranking.setText(equipos.get(listEquipos.getSelectedIndex()).getRanking());
        tfgrupo.setText(equipos.get(listEquipos.getSelectedIndex()).getGrupo());
        tfcopas.setText(equipos.get(listEquipos.getSelectedIndex()).getNumCopas());
        tf01.setText(equipos.get(listEquipos.getSelectedIndex()).getPartido1());
        tf02.setText(equipos.get(listEquipos.getSelectedIndex()).getPartido2());
        tf03.setText(equipos.get(listEquipos.getSelectedIndex()).getPartido3());


    }//GEN-LAST:event_listEquiposValueChanged

    private void listEquiposComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_listEquiposComponentAdded

    }//GEN-LAST:event_listEquiposComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        try {
            TestEquiposFitness test = new TestEquiposFitness();
            test.initialize(" ");
            test.testSelectFittestEquipos();
            String resultado = "Nombre\tRanking\tGrupo\tNumCopas\tPartido 1\tPartido 2\tPartido3\n\n";
            txtFit01.setText(test.fitness01);
            txtganadores01.setText(resultado + test.pequipos01);
            txtconsola.setText("Fitness: " + test.fitness01 + "\nMejor solución: " + test.valor1 + "\nEquipos Mejores posicionados: \n" + test.pequipos01);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        Configuration.reset();

        partidos.equipos.clear();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        Equipos equipoaeditar = new Equipos();
        equipoaeditar.setNombre(tfnombre.getText());
        equipoaeditar.setRanking(tfranking.getText());
        equipoaeditar.setGrupo(tfgrupo.getText());
        equipoaeditar.setNumCopas(tfcopas.getText());
        equipoaeditar.setPartido1(tf01.getText());
        equipoaeditar.setPartido2(tf02.getText());
        equipoaeditar.setPartido3(tf03.getText());

        File archivoEquipos = new File(System.getProperty("user.dir") + "/src/archivos/Mundial.csv");

        // actualizamos valores nuevos
        int a = listEquipos.getSelectedIndex();
        System.out.println("AAAAAA " + a);
        equipos.set(a, equipoaeditar);

        try {
            FileWriter w = new FileWriter(archivoEquipos);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);
            System.out.println("TOTAL EQUIPO " + equipos.size());
            for (int i = 0; i < equipos.size(); i++) {

                // en caso de ser la ultima linea no agregar salto de linea
                if (i == (equipos.size() - 1)) {
                    System.out.println("---------- EQUIPO " + i + " SI " + equipos.get(i).getNombre());
                    wr.write(equipos.get(i).getNombre() + ","
                            + equipos.get(i).getRanking() + ","
                            + equipos.get(i).getGrupo() + ","
                            + equipos.get(i).getNumCopas() + ","
                            + equipos.get(i).getPartido1()
                            + "," + equipos.get(i).getPartido2()
                            + "," + equipos.get(i).getPartido3());

                } else {
                    System.out.println("---------- EQUIPO " + i + " NO " + equipos.get(i).getNombre());

                    wr.write(equipos.get(i).getNombre() + ","
                            + equipos.get(i).getRanking() + ","
                            + equipos.get(i).getGrupo() + ","
                            + equipos.get(i).getNumCopas() + ","
                            + equipos.get(i).getPartido1()
                            + "," + equipos.get(i).getPartido2()
                            + "," + equipos.get(i).getPartido3()
                            + "\n");
                }
            }
            wr.close();
            bw.close();

        } catch (IOException e) {
            e.printStackTrace();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void tfgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgrupoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tfnombre.setText(" ");
        tfranking.setText(" ");
        tfgrupo.setText("");
        tfcopas.setText(" ");
        txtFit01.setText(" ");
        txtconsola.setText(" ");
        txtganadores01.setText(" ");
        tf01.setText(" ");
        tf02.setText(" ");
        tf03.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBrasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBrasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBrasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBrasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBrasil().setVisible(true);
                // Frame frame= new Frame("Titulo de la ventana");
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel fit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listEquipos;
    private javax.swing.JTextField tf01;
    private javax.swing.JTextField tf02;
    private javax.swing.JTextField tf03;
    private javax.swing.JTextField tfcopas;
    private javax.swing.JTextField tfgrupo;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField tfranking;
    private javax.swing.JLabel txtFit01;
    private javax.swing.JTextArea txtconsola;
    private javax.swing.JLabel txtcopasg;
    private javax.swing.JLabel txtfitness;
    private javax.swing.JLabel txtfitness01;
    private javax.swing.JTextArea txtganadores01;
    private javax.swing.JLabel txtnombre;
    private javax.swing.JLabel txtp1;
    private javax.swing.JLabel txtp2;
    private javax.swing.JLabel txtp3;
    private javax.swing.JLabel txtranking;
    // End of variables declaration//GEN-END:variables

}
